### ISSUE TITLE
rook-ceph cannot be deployed from ArgoCD (following this documentation: https://github.com/IBM/cp4waiops-gitops/blob/main/docs/how-to-deploy-cp4waiops-33.md)

### ISSUE THREAD

**Issue by ks-ibm** [IBM/cp4waiops-gitops#124]
Hi!

As per title: I don't see the aforementioned rook-ceph under the config path:

![image](https://user-images.githubusercontent.com/102600916/160621479-47a0efae-2898-47d7-9b39-f7e945501736.png)

Thanks!
K.

**Comment by morningspace** [comment]
@ks-ibm the entries listed in this dropdown box are all helm charts. For a specified path, Argo CD will scan all sub folders underneath and check if they are helm charts, if yes, they will be listed as above.

The reason that you do not see `config/ceph` in the list is simply because it is not a helm chart. We did not make it as a helm chart, because there's nothing needs to be parameterized, all OOTB.

When you see some config not listed in the dropdown box, it doesn't mean you cannot deploy it. Just go ahead to input it in the field manually, in this case, the field value should be `config/ceph`, this will also work.

@liyanwei93 I think we can refine our doc here to clarify this, so as to avoid the misleading.

**Comment by gyliu513** [comment]
can we convert the ceph to a helm chart as well?

**Comment by morningspace** [comment]
Closing it as the corresponding PR has been merged. Now the rook-ceph config is visible in the drop down list as it has been turned into helm chart.
