### ISSUE TITLE
service-account doesn't get synced when following Event Management procedure on https://github.com/IBM/cp4waiops-gitops/blob/main/docs/how-to-deploy-cp4waiops-33.md

### ISSUE THREAD

**Issue by ks-ibm** [IBM/cp4waiops-gitops#125]
Hi!

As per title:
![image](https://user-images.githubusercontent.com/102600916/160621937-a7263aae-716c-4003-b3f7-fe41cb9a2daa.png)

Gives in diff yaml:
![image](https://user-images.githubusercontent.com/102600916/160622021-19475d8e-3949-47cb-871e-254ca4d0c00d.png)

Following up with the team tomorrow morning.

Thanks!
K

**Comment by gyliu513** [comment]
anything wrong with ignorefield?

**Comment by morningspace** [comment]
First of all, I'd say this out-of-sync issue will not impact the install process. It is just the "noise" that makes people confusing. Of course, we need to fix it, either by code or docs.

Secondly, it should have been fixed by the Argo CD ignoreDifferences settings [here](https://github.com/IBM/cp4waiops-gitops/blob/eef1dd00876298d6d2e5e5d8ae6fbd4025d8a070/config/all-in-one/templates/eventmanager.yaml#L80). However, the reason that it does not work is because @ks-ibm is not using this Argo CD app stored in git repo in the [all-in-one helm chart](https://github.com/IBM/cp4waiops-gitops/tree/main/config/all-in-one), but instead, to install event-manager by directly creating an Argo CD app on the fly. If we look at the Argo CD app on that env, there is no such ignoreDifferences there.

This gives us a nice indicator that ultimately I think we need the additional Argo CD app to customize the Argo CD default behavior, which has already been implemented in the all-in-one helm chart [here](https://github.com/IBM/cp4waiops-gitops/blob/main/config/all-in-one/templates/argocd.yaml), because we can add the ignoreDifferences centrally [like this](https://github.com/IBM/cp4waiops-gitops/blob/main/config/argocd/openshift/argocd.yaml#L15-L17), which will solve the above problem, as it does not rely on adding such ignoreDifferences in each Argo CD app, no matter it's pre-stored in git repo or created by user on the fly.

**Comment by ks-ibm** [comment]
> You mean we can add a section that users can manually deploy the [argocd kind](https://github.com/IBM/cp4waiops-gitops/blob/main/config/argocd/openshift/argocd.yaml) before installation as Prerequisites in the doc?

I did follow the ArgoCD requirement in the doc, but that was an "default" deployment without that ignorefield thingy which is included in the all-in-one (which I didn't pick).

I'll hang in here until the offical GA, and see if my ArgoCD is friendly enough to continu. I'll update this case accordingly.

Thanks @liyanwei93 & @morningspace ! Appreciate the support !
K.

**Comment by ks-ibm** [comment]
Good news! After GA, the ArgoCD deployment continued and this issue with unsynced service-account got straightened out. Ran into another pitfall, but that's for another story!

I think this may be closed now?

**Comment by gyliu513** [comment]
@morningspace @liyanwei93 Can we create the SA procedurally, as a resource, Argo will keep deleting the other secret attached to the account by the operator.

**Comment by nastacio** [comment]
@gyliu513 I don't think that SA can be managed through Argo. Note that the operator (or maybe it is OCP) will try and add more secrets to the SA and Argo will delete those on the next synchronization, which will break the SA. 

The operator and Argo will keep "fighting" each other, adding and removing the secret from the SA.
